version: "3.8"

services:
  database:
    image: mysql:8.0.34
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: myDB
    ports:
      - "3307:3306"


  backend:
    container_name: backend
    env_file:
      ../Backend/.env
    build:
      context: ../Backend
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      RABBIT_HOST: rabbitmq
    depends_on:
      - database
    restart: on-failure




  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.12.11-management
    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      #RABBITMQ_DEFAULT_VHOST: "/"

    command:
      - bash
      - -c
      - |
        rabbitmq-plugins enable rabbitmq_web_stomp && rabbitmq-plugins enable rabbitmq_web_stomp_examples && rabbitmq-server

    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf








