spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: LrRfkYXQr6JQKYAyaUaK
            client-secret: 5b4QYad7zQ
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
              client-id: 73d5fa88e8b34b2f6d817b48eaee2c86
              client-secret: IbCMcGnCl60yTkiGAEhWSpUUNc1mx345
              redirect-uri: http://localhost:8080/login/oauth2/code/kakao
              client-authentication-method: client_secret_post
              authorization-grant-type: authorization_code
              scope: profile_nickname, profile_image
              client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


